import Head from "next/head";
function CustomHead() {
  return (
    <>
      <Head>
        <title>Edutech Website | Hashedin by deloitte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://hashedin.com/wp-content/uploads/2019/09/hashedin_logo_white-150x150.png" sizes="32x32"/>
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
    </>
  );
}
export default CustomHead;